PLUGIN_NAME = dof_fp
OBJ         = dof_fp dof_fp_epo 
OBJ_FULL    = $(addsuffix .$(OBJ_SUFFIX), $(OBJ))
LIBS	    = 
LIBS_MINGW32= ../../lib/glt.lib
LIBS_LINUX  = -lglt
CCOPTS_MINGW32 = -I/usr/share/nvidia/include

include ../main.mak

