PLUGIN_NAME = blurtext
OBJ         = blurtext_epopeia blurtext interp
OBJ_FULL    = $(addsuffix .$(OBJ_SUFFIX), $(OBJ))
LIBS	    = 
LIBS_MINGW32= ../../lib/glt.lib
LIBS_LINUX  = -lglt

include ../main.mak

