PLUGIN_NAME = sound_ogg
OBJ        = sound_ogg sound_ogg_epopeia oss_out
OBJ_FULL   = $(addsuffix .$(OBJ_SUFFIX), $(OBJ))
LIBS	    = 
LIBS_LINUX  = -lm /usr/lib/libvorbisfile.a /usr/lib/libvorbis.a /usr/lib/libogg.a -lpthread
CCOPTS_LINUX = 


include ../main.mak

