CC=cl
CFLAGS=/Ox /Zi /G5As /DWINDOZE /DWIN32  /c /I../../../src/include

OBJS   = fantasy.obj carga.obj misc.obj vista.obj raster.obj mates.obj textura.obj quatern.obj material.obj interp.obj fantasy_api.obj
DST    = fantasy.lib



$(DST) : $(OBJS)
	lib  /out:$(DST) $(OBJS) ../../../src/epopeia.lib

.cpp.obj:
	$(CC) -c $(CFLAGS) $<

clean:
	del *.obj
	del *.lib
