PLUGIN_NAME = graphics_sdl
OBJ        = graphics_sdl graphics_sdl_epopeia keyboard_sdl
OBJ_FULL   = $(addsuffix .$(OBJ_SUFFIX), $(OBJ))
#LIBS	    = 
#LIBS_MINGW32= ../../lib/
LIBS_LINUX  = -lSDL


include ../main.mak

