# Epopeia demosystem makefile
# for GNU make
# by Enlar 2002-2003

# Wrapper Makefile para mayor comodidad.
# Hay que definir la variable de entorno PLATFORM para poder usarlo:
#  linux
#  win32

# incluimos makefile correspondiente a la plataforma

include makefile.$(PLATFORM)

