PLUGIN_NAME = menu_win32
OBJ         = dlg iface/button iface/hlink iface/tooltip menu_win32_epopeia res/resource
OBJ_FULL    = $(addsuffix .$(OBJ_SUFFIX), $(OBJ))
LIBS	    = ../../lib/fmodvc.lib
#LIBS_MINGW32= ../../lib/
LIBS_LINUX  = -lfmod


include ../main.mak

