PLUGIN_NAME = graphics_wgl
OBJ         = graphics_wgl keyboard_tds graphics_wgl_epopeia
OBJ_FULL    = $(addsuffix .$(OBJ_SUFFIX), $(OBJ))
LIBS_WIN32  = opengl32.lib glu32.lib glaux.lib 
#LIBS_MINGW32= ../../lib/
LIBS_LINUX  =

include ../main.mak

